### PR TITLE
Add planned architecture

### PR DESCRIPTION
**Pull request by mlangbehn**
Add planned architecture to `README.md` including:
* Diagram of layout
* Chronology of events

Signed-off-by: Matt Langbehn <matthew.langbehn@gmail.com>

### CODE REVIEW

**Review by paulczar — APPROVED** [review]
:+1:   @animeshsingh  ?

**Comment by animeshsingh** [comment]
we need one more openwhisk action - the second openwhisk action is triggered when something gets stroed in db to trigger the analysis tool. Else good to go

**Comment by paulczar** [comment]
I would expect to have the dashboard app do the analysis and produce the graphs when prompted by the user what they want to see. ( timeframe, etc )

If the data is big enough I could see a need to do a mapreduce type action on a cron task, but you certainly wouldn't do it on every database insertion.

**Comment by animeshsingh** [comment]
so the data here is coming every two weeks, and that`s the only time its isnerted. The whole idea is to make this event triggered application, one event is a cron job, the 2nd event is when new data comes in to database to push to analysis tool to prepare some reports

**Pull request merged**
